# Site settings
title: Jelly Invoice (Alfa)
email: michael@rurkadesign.com

billing-address: "<b>Michael Rurka</b> <br>1991 November Dr, <br>Suite 11-26, <br>Canada, NB <br>Business Number: RUD3-551991"
business-number: "RUD3-551991"

baseurl: "/jelly-invoice" # the subpath of your site, e.g. /blog
url: "http://mrurka.github.io" # the base hostname & protocol for your site