# Site settings
title: Jelly Invoice
email: michael@rurkadesign.com

business-name: "Rurka Design"
business-number: "RUD3-551991"
billing-address: "Michael Rurka <br>1991 November Dr, <br>Suite 11-26, <br>Canada, NB <br>Business Number: RUD3-551991"

baseurl: "/jelly-invoice" # the subpath of your site, e.g. /blog
url: "http://mrurka.github.io" # the base hostname & protocol for your site